
# !/usr/bin/env python3
"""HA-LMAPF Ablation Study — main runner.

Runs two ablation groups (A/B) that justify the key architectural and
safety design decisions in the system.

Ablation groups
---------------
  A  Tier Architecture    — what does each system tier contribute?
  B  Safety & Perception  — hard safety vs soft safety vs no safety

Maps (2 small maps, matching lifelong agent-sweep study)
--------------------------------------------------------
  random           data/maps/random-64-64-10.map        (50 agents, 20 humans)
  warehouse_small  data/maps/warehouse-10-20-10-2-1.map (250 agents, 100 humans)

Statistical methodology
-----------------------
  • 10 seeds (default); same seed used for control and every ablation
    condition → paired Wilcoxon signed-rank test (maximum power).
  • Friedman omnibus test within each group before pairwise comparisons.
  • Benjamini-Hochberg FDR correction within each group.
  • Rank-biserial r AND Cohen's d as standardized effect sizes.
  • Shapiro-Wilk test on paired differences (justifies non-parametric).
  • Post-hoc power analysis for each pairwise comparison.
  • 95 % bootstrap confidence intervals (BCa when n ≥ 10).
  • Multi-map and scale-sensitivity support for generalization.
  • Optional warm-up exclusion for steady-state analysis.
  • Results: results.csv, summary.csv, table.tex, per-group CSVs.

Usage
-----
  # Full study (all groups, 10 seeds, all cores)
  python scripts/ablation/run_ablation_study.py --workers 0

  # Specific group only
  python scripts/ablation/run_ablation_study.py --groups A --workers 0

  # Multi-map study (both small maps)
  python scripts/ablation/run_ablation_study.py \\
      --maps random warehouse_small --workers 0

  # Quick smoke-test (1 seed, 200 steps, group A only)
  python scripts/ablation/run_ablation_study.py --sanity

Output
------
  logs/ablation/<label>_<timestamp>/
  ├── results.csv          raw per-(condition,seed) data
  ├── summary.csv          aggregated stats vs full_system
  ├── table.tex            booktabs LaTeX table (copy-paste to paper)
  ├── group_A_results.csv  per-group raw data
  ├── group_A_summary.csv  per-group aggregated stats
  ├── ...
  └── plots/               generated by plot_ablation.py
"""

from __future__ import annotations

import argparse
import csv
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from scripts.ablation.ablation_utils import (
    ABLATION_CONDITIONS, CONDITION_ORDER, GROUP_LABELS, GROUP_ORDER,
    MAP_DEFAULTS, MAPS_ALL, PRIMARY_MAP,
    add_common_args, aggregate_ablation_results, get_base_config,
    make_output_dir, print_group_summary, resolve_workers,
    run_ablation_group, save_results,
)


def _save_group_csv(
        results: list, aggregated: list, group: str, out: Path
) -> None:
    """Save per-group raw + summary CSVs alongside the main outputs."""
    grp_raw = [r for r in results if r.get("group") == group]
    grp_agg = [r for r in aggregated if r.get("group") == group]

    if grp_raw:
        p = out / f"group_{group}_results.csv"
        with open(p, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=grp_raw[0].keys())
            writer.writeheader()
            writer.writerows(grp_raw)

    if grp_agg:
        p = out / f"group_{group}_summary.csv"
        with open(p, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=grp_agg[0].keys())
            writer.writeheader()
            writer.writerows(grp_agg)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="HA-LMAPF ablation study (Groups A & B)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples
--------
Full study (groups A & B, 10 seeds, all CPU cores):
  python scripts/ablation/run_ablation_study.py --workers 0

Architecture ablation only:
  python scripts/ablation/run_ablation_study.py --groups A --workers 0

Multi-map study (both small maps):
  python scripts/ablation/run_ablation_study.py \\
      --maps random warehouse_small --workers 0

After running, generate figures:
  python scripts/ablation/plot_ablation.py \\
      logs/ablation/<timestamp>/summary.csv
""",
    )
    add_common_args(parser)
    parser.add_argument(
        "--groups",
        nargs="+",
        choices=GROUP_ORDER,
        default=GROUP_ORDER,
        help=(
            f"Ablation groups to run (default: all {GROUP_ORDER}). "
            "A=architecture  B=safety"
        ),
    )
    parser.add_argument(
        "--list-conditions",
        action="store_true",
        help="Print all ablation conditions and exit.",
    )
    parser.add_argument(
        "--sanity",
        action="store_true",
        help="Quick smoke-test: 1 seed, 200 steps, group A only",
    )
    args = parser.parse_args()

    if args.list_conditions:
        for group in GROUP_ORDER:
            print(f"\nGroup {group}: {GROUP_LABELS[group]}")
            for name in CONDITION_ORDER:
                cond = ABLATION_CONDITIONS[name]
                if cond["group"] == group:
                    print(f"  {name:<30}  {cond['description'][:65]}")
        return

    args.workers = resolve_workers(args.workers)

    if args.sanity:
        args.seeds = [0]
        args.steps = 200
        args.groups = ["A"]
        print("\n  ** SANITY MODE: 1 seed, 200 steps, group A only **")

    base = get_base_config(
        map_path=args.map,
        num_agents=args.agents,
        num_humans=args.humans,
        steps=args.steps,
        horizon=args.best_horizon,
        replan_every=args.best_replan_every,
        fov_radius=args.best_fov_radius,
        safety_radius=args.best_safety_radius,
        commit_horizon=args.best_commit_horizon,
        delay_threshold=args.best_delay_threshold,
    )

    out = make_output_dir(run_label=args.label, base_dir=args.output)

    # ── Print study configuration ───────────────────────────────────────
    print(f"\n{'=' * 60}")
    print("HA-LMAPF Ablation Study")
    print(f"{'=' * 60}")
    print(f"Groups:        {args.groups}")
    print(f"Seeds:         {len(args.seeds)} ({args.seeds[0]}..{args.seeds[-1]})")
    print(f"Steps/run:     {args.steps}")
    print(f"Map:           {args.map}")
    print(f"Agents:        {args.agents}  Humans: {args.humans}")
    print(f"Solver:        lacam3")
    print(f"Horizon:       {args.best_horizon}  replan_every: {args.best_replan_every}")
    print(f"fov_radius:    {args.best_fov_radius}  safety_radius: {args.best_safety_radius}")
    n_conditions = sum(
        1 for name in CONDITION_ORDER
        if ABLATION_CONDITIONS[name]["group"] in args.groups
        or name == "full_system"
    )
    # unique conditions across all selected groups
    selected_conds = set()
    for g in args.groups:
        for name in CONDITION_ORDER:
            if ABLATION_CONDITIONS[name]["group"] == g or name == "full_system":
                selected_conds.add(name)
    n_runs = len(selected_conds) * len(args.seeds)
    print(f"Conditions:    {len(selected_conds)} unique  ({n_runs} total runs)")
    print(f"Workers:       {args.workers}")
    print(f"Output:        {out}")
    print(f"{'=' * 60}")

    # ── Resolve maps and scale configs ──────────────────────────────────
    map_list = [args.map]
    if args.maps:
        map_list = []
        for m in args.maps:
            if m in MAPS_ALL:
                map_list.append(MAPS_ALL[m])
            else:
                map_list.append(m)

    scale_configs = [(args.agents, args.humans)]
    if args.scale_configs:
        scale_configs = []
        for sc in args.scale_configs:
            a, h = sc.split(":")
            scale_configs.append((int(a), int(h)))

    warmup_steps = args.warmup_steps

    # ── Run selected groups ─────────────────────────────────────────────
    all_results = []
    t_start = time.time()

    for map_path in map_list:
        for n_agents, n_humans in scale_configs:
            # Use per-map defaults when running multi-map with default scale
            if args.maps and not args.scale_configs and map_path in MAP_DEFAULTS:
                n_agents = MAP_DEFAULTS[map_path]["num_agents"]
                n_humans = MAP_DEFAULTS[map_path]["num_humans"]
            scenario_base = get_base_config(
                map_path=map_path,
                num_agents=n_agents,
                num_humans=n_humans,
                steps=args.steps,
                horizon=args.best_horizon,
                replan_every=args.best_replan_every,
                fov_radius=args.best_fov_radius,
                safety_radius=args.best_safety_radius,
                commit_horizon=args.best_commit_horizon,
                delay_threshold=args.best_delay_threshold,
            )
            if warmup_steps > 0:
                scenario_base["warmup_steps"] = warmup_steps

            scenario_tag = (
                f"{Path(map_path).stem}_a{n_agents}_h{n_humans}"
            )
            if len(map_list) > 1 or len(scale_configs) > 1:
                print(f"\n{'#' * 60}")
                print(f"Scenario: {scenario_tag}")
                print(f"{'#' * 60}")

            for group in args.groups:
                results = run_ablation_group(
                    group_id=group,
                    seeds=args.seeds,
                    base_config=scenario_base,
                    verbose=args.verbose,
                    workers=args.workers,
                )
                # Tag each result with scenario metadata
                for r in results:
                    r["map"] = map_path
                    r["map_name"] = Path(map_path).stem
                    r["num_agents"] = n_agents
                    r["num_humans"] = n_humans
                    r["warmup_steps"] = warmup_steps
                all_results.extend(results)

    # ── Aggregate ───────────────────────────────────────────────────────
    aggregated = aggregate_ablation_results(all_results)

    # ── Save combined outputs ───────────────────────────────────────────
    save_results(all_results, aggregated, out, latex=not args.no_latex)

    # Save per-group CSVs
    for group in args.groups:
        _save_group_csv(all_results, aggregated, group, out)
        print(f"Saved group {group} CSVs.")

    # ── Print summaries ─────────────────────────────────────────────────
    for group in args.groups:
        print_group_summary(
            aggregated, group,
            primary="throughput",
            secondary=["mean_flowtime", "near_misses", "total_wait_steps"],
        )

    # Also print safety summary for Groups B
    if "B" in args.groups:
        print("\n── Group B: Safety metrics ──")
        print_group_summary(
            aggregated, "B",
            primary="near_misses",
            secondary=[
                "safety_violations", "collisions_agent_human",
                "throughput",
            ],
        )

    # ── Final timing ────────────────────────────────────────────────────
    total_min = (time.time() - t_start) / 60
    print(f"\n{'=' * 60}")
    print(f"Study complete: {len(all_results)} runs in {total_min:.1f} min")
    print(f"Output:  {out}")
    print(f"\nNext step — generate all paper figures:")
    print(f"  python scripts/ablation/plot_ablation.py \\")
    print(f"      {out}/summary.csv")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
